# Generated by Django 3.0.3 on 2020-02-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0002_contato_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%M/%D'),
        ),
    ]
